# =============================================================================
# Integration tests - run component in real GitLab pipelines
# =============================================================================

test-pipelines::javabuild:
  interruptible: true
  needs: [build-component-image]
  parallel:
    matrix:
      - TEST_PATH:
          - javabuild/pass
          - javabuild/fail
        JAVA_VERSION:
          - 21
          - 25
  stage: test-pipelines
  trigger:
    include:
      - local: pipeline/test-pipelines/$TEST_PATH.gitlab-ci.yml
        inputs:
          java_version: "$JAVA_VERSION"
    strategy: depend
