spec:
  component: [name, sha, version]
  inputs:
    java_version:
      default: "25"
      description: "Java version"
      options: ["21", "25"]
      type: string
    # Standard Component inputs
    component_context_dir:
      default: "./"
      description: "Working directory in which this Component will execute"
      regex: ^([a-z.][a-zA-Z0-9-_/]+)?$
      type: string
    job_name_prefix:
      default: ""
      description: "Prefix for all component jobs"
      regex: ^([a-z][a-z0-9-]+::)*$
      type: string
    job_stage_install:
      default: "install"
      description: "Pipeline stage for dependency installation"
      type: string
    job_stage_build:
      default: "build"
      description: "Pipeline stage for build"
      type: string
---
include:
  - local: /templates/shared/common.yml
    inputs:
      component_context_dir: "$[[ inputs.component_context_dir ]]"
      job_name_prefix: "$[[ inputs.job_name_prefix ]]"
      job_stage: "$[[ inputs.job_stage_install ]]"
      _component_image: "$CI_TEMPLATE_REGISTRY_HOST/dwp/engineering/pipeline-solutions/gitlab/components/java:$[[ component.sha ]]-jdk$[[ inputs.java_version ]]"

# Maven dependencies - install stage
"$[[ inputs.job_name_prefix ]]java::build::dependencies":
  artifacts:
    expire_in: 1 week
    paths:
      - $[[ inputs.component_context_dir ]]/.m2-local/
  cache:
    key: "${CI_JOB_NAME}-$[[ inputs.java_version ]]"
    paths:
      - $[[ inputs.component_context_dir ]]/.m2-local/
    when: always
  extends: ".$[[ inputs.job_name_prefix ]]java::common"
  stage: $[[ inputs.job_stage_install ]]
  script: |
    mvn dependency:go-offline \
      -Dmaven.repo.local=.m2-local \
      -s /component/shared/settings.xml

# Maven package - build stage
"$[[ inputs.job_name_prefix ]]java::build::package":
  artifacts:
    expire_in: 1 week
    paths:
      - $[[ inputs.component_context_dir ]]/target/*.jar
  cache:
    key: "${CI_JOB_NAME}-$[[ inputs.java_version ]]"
    paths:
      - $[[ inputs.component_context_dir ]]/.m2-local/
    when: always
  extends: ".$[[ inputs.job_name_prefix ]]java::common"
  needs:
    - job: "$[[ inputs.job_name_prefix ]]java::build::dependencies"
      optional: true
  stage: $[[ inputs.job_stage_build ]]
  script: |
    mvn package -DskipTests \
      -Dmaven.repo.local=.m2-local \
      -s /component/shared/settings.xml
